import { describe, expect, it } from "vitest";
import { featureRegistry } from "../src/features/index.js";
import { generateFeatureCatalogMarkdown } from "../src/framework/catalog-documentation.js";
import {
  defineFeature,
  frameworkApiVersion
} from "../src/framework/index.js";
import { createFeatureRegistry } from "../src/framework/internal.js";

describe("Generated feature catalog", () => {
  it("derives installed commands, actions, routes, events, and schedules", () => {
    const markdown = generateFeatureCatalogMarkdown(featureRegistry, {
      workspacePackages: [
        {
          packageName: "@elmybot/feature-alive",
          featureId: "core.alive",
          installed: true
        }
      ]
    });

    expect(markdown).toContain("Generated by `npm run feature:docs`");
    expect(markdown).toContain("Framework API: v1.");
    expect(markdown).toContain("## Shareable state declarations");
    expect(markdown).toContain("## Workspace packages");
    expect(markdown).toContain("`@elmybot/feature-alive` | `core.alive` | yes");
    expect(markdown).toContain("`core.alive` | `@elmybot/feature-alive`");
    expect(markdown).toContain("`/counter`");
    expect(markdown).toContain("Command | Type | Access | Description");
    expect(markdown).toContain(
      "fun.deaths | `/deaths` | action | public; framework.moderators when " +
      "`operation` is present and is not `check`"
    );
    expect(markdown).toContain(
      "fun.deaths | `!deaths` | action | public; framework.moderators when " +
      "`operation` is present and is not `check`"
    );
    expect(markdown).toContain(
      "`fun.deaths.manage.v1` | discord, twitch | public; " +
      "framework.moderators when `operation` is present and is not `check`"
    );
    expect(markdown).toContain("`!announce`");
    expect(markdown).toContain("`integration.announcement.publish.v1`");
    expect(markdown).toContain("`twitch.stream-online-to-discord.v1`");
    expect(markdown).toContain("`twitch.stream.online.v1`");
    expect(markdown).toContain("`discord.integration.announce-twitch-random.v1`");
  });

  it("documents normalized shareable-state declarations without state values", () => {
    const registry = createFeatureRegistry([
      defineFeature({
        apiVersion: frameworkApiVersion,
        id: "fun.score",
        description: "Tracks one shareable score.",
        shareableState: [{
          id: "score",
          label: "Shared score",
          schemaVersion: 2,
          compatibleVersions: [1, 2],
          collisionSummary: { kind: "entry_count" },
          limits: { maxEntries: 4, maxValueBytes: 256 }
        }]
      })
    ]);
    const markdown = generateFeatureCatalogMarkdown(registry);

    expect(markdown).toContain(
      "fun.score | `score` | Shared score | 2 | 1, 2 | entry_count | " +
      "4 entries; 256 bytes/value"
    );
  });
});
