import { describe, expect, it } from "vitest";
import { featureRegistry } from "../src/features/index.js";
import { generateFeatureCatalogMarkdown } from "../src/framework/catalog-documentation.js";

describe("Generated feature catalog", () => {
  it("derives installed commands, actions, routes, events, and schedules", () => {
    const markdown = generateFeatureCatalogMarkdown(featureRegistry);

    expect(markdown).toContain("Generated by `npm run feature:docs`");
    expect(markdown).toContain("Framework API: v1.");
    expect(markdown).toContain("`/counter`");
    expect(markdown).toContain("`!announce`");
    expect(markdown).toContain("`integration.announcement.publish.v1`");
    expect(markdown).toContain("`twitch.stream-online-to-discord.v1`");
    expect(markdown).toContain("`twitch.stream.online.v1`");
    expect(markdown).toContain("`discord.integration.announce-twitch-random.v1`");
  });
});
