import { describe, expect, it } from "vitest";
import { featureRegistry } from "../src/features/index.js";
import { generateFeatureCatalogMarkdown } from "../src/framework/catalog-documentation.js";
import {
  defineDurableEventStream,
  defineFeature,
  frameworkApiVersion
} from "../src/framework/index.js";
import { createFeatureRegistry } from "../src/framework/internal.js";

describe("Generated feature catalog", () => {
  it("derives installed commands, actions, routes, events, and schedules", () => {
    const markdown = generateFeatureCatalogMarkdown(featureRegistry, {
      workspacePackages: [
        {
          packageName: "@elmybot/feature-alive",
          featureId: "core.alive",
          installed: true
        }
      ]
    });

    expect(markdown).toContain("Generated by `npm run feature:docs`");
    expect(markdown).toContain("Framework API: v1.");
    expect(markdown).toContain(
      "Consumer guide for `widget.data`: [widget data](widget-data.md)."
    );
    expect(markdown).toContain("## Shareable state declarations");
    expect(markdown).toContain("## Readable state exports");
    expect(markdown).toContain("## Durable event streams");
    expect(markdown).toContain("## Platform event triggers");
    expect(markdown).toContain("## Workspace packages");
    expect(markdown).toContain("`@elmybot/feature-alive` | `core.alive` | yes");
    expect(markdown).toContain("`core.alive` | `@elmybot/feature-alive`");
    expect(markdown).toContain("`/counter`");
    expect(markdown).toContain("Command | Type | Access | Description | Example");
    expect(markdown).toContain('`!deaths check "Dark Souls"`');
    expect(markdown).toContain("`/deaths operation:check game:Dark Souls`");
    expect(markdown).toContain(
      "fun.deaths | `/deaths` | action | public; framework.moderators when " +
      "`operation` is present and is not `check`"
    );
    expect(markdown).toContain(
      "fun.deaths | `!deaths` | action | public; framework.moderators when " +
      "`operation` is present and is not `check`"
    );
    expect(markdown).toContain(
      "`fun.deaths.manage.v1` | discord, twitch | public; " +
      "framework.moderators when `operation` is present and is not `check`"
    );
    expect(markdown).toContain("`!announce`");
    expect(markdown).toContain("`integration.announcement.publish.v1`");
    expect(markdown).toContain("`twitch.stream-online-to-discord.v1`");
    expect(markdown).toContain("`twitch.stream.online.v1`");
    expect(markdown).toContain("`discord.integration.announce-twitch-random.v1`");
  });

  it("documents durable event declarations without stream values or internals", () => {
    const registry = createFeatureRegistry([
      defineFeature({
        apiVersion: frameworkApiVersion,
        id: "widget.events",
        description: "Publishes widget events.",
        eventStreams: [
          defineDurableEventStream({
            id: "updates",
            version: 1,
            label: "Widget events",
            description: "Events for an authorized widget.",
            platforms: ["discord", "twitch"],
            scope: { kind: "effective_shareable" },
            access: { kind: "operator_grant" },
            payload: {
              schema: {
                type: "object",
                properties: {
                  data: { type: "string", minLength: 1, maxLength: 400 }
                },
                required: ["data"]
              }
            }
          })
        ]
      })
    ]);
    const markdown = generateFeatureCatalogMarkdown(registry);

    expect(markdown).toContain(
      "widget.events | `updates` | 1 | discord, twitch | effective_shareable | " +
      "operator_grant | object | bounded_at_least_once; 1 consumer; 1800s; " +
      "1000 events; 1048576 bytes"
    );
    expect(markdown).not.toContain("physical stream");
    expect(markdown).not.toContain("payload value");
  });

  it("documents normalized shareable-state declarations without state values", () => {
    const registry = createFeatureRegistry([
      defineFeature({
        apiVersion: frameworkApiVersion,
        id: "fun.score",
        description: "Tracks one shareable score.",
        shareableState: [{
          id: "score",
          label: "Shared score",
          schemaVersion: 2,
          compatibleVersions: [1, 2],
          collisionSummary: { kind: "entry_count" },
          limits: { maxEntries: 4, maxValueBytes: 256 }
        }]
      })
    ]);
    const markdown = generateFeatureCatalogMarkdown(registry);

    expect(markdown).toContain(
      "fun.score | `score` | Shared score | 2 | 1, 2 | entry_count | " +
      "4 entries; 256 bytes/value | —"
    );
    expect(generateFeatureCatalogMarkdown(featureRegistry)).toContain(
      "fun.deaths | `game_deaths` | Per-game death counts | 1 | 1 | " +
      "entry_count | 100 entries; 16384 bytes/value | integrationState"
    );
    expect(generateFeatureCatalogMarkdown(featureRegistry)).toContain(
      "fun.deaths | `count` | 1 | lookup | discord, twitch | " +
      "effective_shareable | operator_grant | game | object | default | —"
    );
    expect(generateFeatureCatalogMarkdown(featureRegistry)).toContain(
      "fun.deaths | `counts` | 1 | collection | discord, twitch | " +
      "effective_shareable | operator_grant | — | array | default | explicit"
    );
    expect(generateFeatureCatalogMarkdown(featureRegistry)).toContain(
      "widget.data | `latest` | 1 | value | discord, twitch | " +
      "effective_shareable | operator_grant | — | object | absent | —"
    );
  });
});
